from playwright.sync_api import Page, expect


def test_login(page: Page):
    page.goto('https://the-internet.herokuapp.com/')
    search_auth_link = page.get_by_role("link", name="Form Authentication")
    search_auth_link.click()
    search_user_name = page.get_by_role("textbox", name="username")
    search_user_name.fill('Alex')
    search_pass = page.get_by_role("textbox", name="password")
    search_pass.fill('Alex@1986')
    search_login_button = page.get_by_role("button", name="Login")
    search_login_button.click()
    flash_message = page.locator("div#flash")
    expect(flash_message).to_be_visible()


def test_form(page: Page):
    page.goto('https://demoqa.com/automation-practice-form')
    search_first_name = page.locator('#firstName')
    search_first_name.fill('Alex')
    search_last_name = page.locator('#lastName')
    search_last_name.fill('Traf')
    email_input = page.locator("#userEmail")
    email_input.fill("test@example.com")
    search_gender = page.locator("label:has-text('Female')")
    search_gender.click()
    input_mobile_number = page.locator("input[placeholder='Mobile Number']")
    input_mobile_number.fill("1234567890")
    date_input = page.locator("input#dateOfBirthInput")
    date_input.click()
    month_dropdown = page.locator("select.react-datepicker__month-select")
    month_dropdown.select_option("5")
    year_dropdown = page.locator("select.react-datepicker__year-select")
    year_dropdown.select_option("2000")
    day_element = page.locator("div.react-datepicker__day--021")
    day_element.click()
    subjects_input = page.locator("input#subjectsInput")
    subjects_input.fill("English")
    subjects_input.press("Enter")
    hobbies = page.locator("label:has-text('Reading')")
    hobbies.click()
    address_input = page.locator("textarea[placeholder='Current Address']")
    address_input.fill("123 Main Street, City, Country")
    state_dropdown = page.locator("div#state div.css-1wa3eu0-placeholder:has-text('Select State')")
    state_dropdown.click()
    input_field = page.locator("input#react-select-3-input")
    input_field.fill("NCR")
    input_field.press("Enter")
    city_dropdown = page.locator("div#city div.css-1wa3eu0-placeholder:has-text('Select City')")
    city_dropdown.click()
    input_field = page.locator("input#react-select-4-input")
    input_field.fill("Delhi")
    input_field.press("Enter")
    submit_button = page.locator("#submit")
    submit_button.click()
    modal_title = page.locator("div.modal-title.h4:has-text('Thanks for submitting the form')")
    expect(modal_title).to_be_visible()
